### ISSUE TITLE
戳一戳的代码逻辑有点小问题

### ISSUE THREAD

**Issue by Echoosx** [LaoLittle/AutoGroup#2]
https://github.com/LaoLittle/AutoGroup/blob/380b564f28910d4fcfbea3d258406b63fa8f63a2/src/main/kotlin/AutoGroup.kt#L258-L266
`Line264` 应该是`nudgedPerReply`而不是`nudgedReply.random()`，不然又会重新随机一次

**Comment by LaoLittle** [comment]
> https://github.com/LaoLittle/AutoGroup/blob/380b564f28910d4fcfbea3d258406b63fa8f63a2/src/main/kotlin/AutoGroup.kt#L258-L266
> 
> 
> `Line264` 应该是`nudgedPerReply`而不是`nudgedReply.random()`，不然又会重新随机一次

可以交个pr

**Comment by LaoLittle** [comment]
#3
