### ISSUE TITLE
群员以匿名身份游玩赌盘会导致框架崩溃

### ISSUE THREAD

**Issue by KaRuichin** [LaoLittle/AutoGroup#4]
如以下两图所示，如需提供其他信息请提出>_<
![F3KBXK43 74%7Y2OGDO% @6](https://user-images.githubusercontent.com/69111766/150714394-eeef5449-5658-4987-95a2-ad3784eba0ec.png)
![image](https://user-images.githubusercontent.com/69111766/150714372-aac8fbf8-b850-459b-9aec-83bacd5efd8c.png)
以上。

**Comment by LaoLittle** [comment]
mirai版本是？

**Comment by LaoLittle** [comment]
这应该是`mirai-native`的问题，请移步[mirai-native](https://github.com/iTXTech/mirai-native)

**Comment by KaRuichin** [comment]
刚刚尝试未加载`mirai-native`再复现一下确实正常了(
打扰了，感谢积极回复。
