### ISSUE TITLE
多个Bot复读导致QQ端卡顿

### ISSUE THREAD

**Issue by greenhandzdl** [LaoLittle/AutoGroup#5]
客户端：MA
具体问题：如xx群员Bot设置x自动回答x（复读），则MA端Bot也会继续复读
额外条件：在Wlan（特别差的那种），更有可能触发
希望：复读加上更多条件的设置，如：随机复读
另外，打断施法不是更折磨群友的事情吗？要不再加上个随机发送乱码防止被恶意复读（如果Bot触犯复读条件，则先复读再打断）

**Comment by greenhandzdl** [comment]
刚刚复读的时候发现冷却好像没用，然后还跳了一堆的error（

**Comment by greenhandzdl** [comment]
> 刚刚复读的时候发现冷却好像没用，然后还跳了一堆的error（

嗯，是 jieba-analysis报的错，另外我没用安装这个插件（

**Comment by LaoLittle** [comment]
> 刚刚复读的时候发现冷却好像没用，然后还跳了一堆的error（

error呢

**Comment by LaoLittle** [comment]
> > 刚刚复读的时候发现冷却好像没用，然后还跳了一堆的error（
> 
> 嗯，是 jieba-analysis报的错，另外我没用安装这个插件（

jieba是内置的，可能安卓并不支持
不过那个是给淫语翻译机用的啊

**Comment by greenhandzdl** [comment]
对，淫语翻译好像用不了（我刚刚去群试过了，报错跟那个差不多一致
这样啊？就有一个Bug一个适配问题了？¿

**Comment by greenhandzdl** [comment]
草，又发现了盲点，bot在第三次成员复读后，就会加入复读，你复读一遍，bot100%会跟着复读，冷却跟没设置一样

**Comment by greenhandzdl** [comment]
![Screenshot_2022-01-27-21-59-36-885_io.github.mzdluo123.mirai.android.jpg](https://user-images.githubusercontent.com/61241103/151373472-c793b9ae-8668-4be0-8c33-35a1757a8ce5.jpg)
那个sb冷却（

**Comment by greenhandzdl** [comment]
![Screenshot_20220206_163008_io github mzdluo123 mirai android](https://user-images.githubusercontent.com/61241103/152673228-48a75e02-545a-4685-92ba-be9596397e6a.jpg)
![Screenshot_20220206_163003_io github mzdluo123 mirai android](https://user-images.githubusercontent.com/61241103/152673238-b1df4c86-ac0c-4f4d-b193-aded16754e25.jpg)
用了几天后发现报错更加的严重了，而且bot莫名其妙被沉默了

**Comment by LaoLittle** [comment]
mirai安卓没经过测试的（）

**Comment by greenhandzdl** [comment]
为什么你们都用jieba。。。
另一个plugins也因为jieba翻车了（词云，但好像修复了）

**Comment by greenhandzdl** [comment]
MA应该是废了，转mcl了
