### ISSUE TITLE
戳一戳没反应是为什么(

### ISSUE THREAD

**Issue by Cicini** [LaoLittle/AutoGroup#6]
没有报错，也没有信息提示 (

**Comment by KaRuichin** [comment]
Bot登录的协议是`ANDROID_PHONE`吗？
只有`ANDROID_PHONE`协议可以接收戳一戳消息，你可以在`.\config\Console\AutoLogin.yml`更改登录协议。
![image](https://user-images.githubusercontent.com/69111766/152918979-978bfaca-83bd-4110-8e40-5b12e5f867ce.png)

**Comment by Cicini** [comment]
明白了（ 设置的PAD
